/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package ch.so.agi.sostat

class App {
    static void main(String[] args) {

        def statMap = new StatMap()
        statMap.create()




    }
}
